name: build
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
      - run: npm install
      - run: ng build -c production
      - run: docker build -t raagpc/gif-converter-frontend .
      - run: docker push raagpc/gif-converter-frontend 
      - run: docker-compose rm -s
      - run: docker-compose -f docker-compose.yml up -d --force-recreate

